# Generated by Django 2.0.3 on 2018-04-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='hash',
            field=models.CharField(blank=True, default='NA', max_length=64),
        ),
    ]
