# Generated by Django 2.0.3 on 2018-03-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180329_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
