# Generated by Django 2.0.3 on 2018-03-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_workflow_client_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
