# Generated by Django 2.0.3 on 2018-03-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_workflow_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
