# Generated by Django 2.0.3 on 2018-03-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20180331_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='keywords',
            field=models.CharField(default='', max_length=256),
        ),
    ]
