# Generated by Django 2.0.3 on 2018-04-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20180331_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='likes',
            new_name='downloads',
        ),
    ]
