# Generated by Django 2.0.3 on 2018-04-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_workflow_jsonfilename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='jsonFileName',
        ),
    ]
