# Generated by Django 2.0.3 on 2018-04-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_workflow_jsonfilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='tooltip',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
