# Generated by Django 2.0.3 on 2018-04-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_workflow_tooltip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='tooltip',
        ),
        migrations.AddField(
            model_name='category',
            name='tooltip',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
