# Generated by Django 2.0.3 on 2018-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20180405_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='versionEnd',
            field=models.CharField(blank=True, default='-1', max_length=128),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='versionInit',
            field=models.CharField(max_length=128),
        ),
    ]
