RECAPTCHA_PUBLIC_KEY = '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
RECAPTCHA_PRIVATE_KEY = '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'

# REAL KEYS
# RECAPTCHA_PUBLIC_KEY = '6LccnlEUAAAAAFLXs4MAqi8dBXPGCOJA0ZkIFJ1o'
# RECAPTCHA_PRIVATE_KEY = '6LccnlEUAAAAAPOMltCDCo17K-66a7Z2R2zHMfbR'
